import java.util.*;

class Main {

    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);
        int n = sc.nextInt();
        int num = n;   // store original value

        
        System.out.print(n + " ");

        while (n != 1) {
            if (n % 2 == 0) {
                n = n / 2;
            } else {
                n = 3 * n + 1;
            }
            System.out.print(n + " ");
        }

       
        int maxLength = 0;
        int maxLengthEle = 0;

        for (int i = 1; i <= num; i++) {
            int length = findLength(i);

            if (length > maxLength) {
                maxLength = length;
                maxLengthEle = i;
            }
        }

        System.out.print("\nMax Length: " + maxLength + 
                         " Generated By: " + maxLengthEle);

        
        int maxValue = 0;
        int maxValueEle = 0;

        for (int k = 1; k <= num; k++) {

            int temp = k;

            // check starting value
            if (temp > maxValue) {
                maxValue = temp;
                maxValueEle = k;
            }

            while (temp != 1) {
                if (temp % 2 == 0) {
                    temp = temp / 2;
                } else {
                    temp = temp * 3 + 1;
                }

                if (temp > maxValue) {
                    maxValue = temp;
                    maxValueEle = k;
                }
            }
        }

        System.out.print("\nMax Value: " + maxValue + 
                         " Generated By: " + maxValueEle);
    }

  
    public static int findLength(int n) {
        int count = 1;  

        while (n != 1) {
            if (n % 2 == 0)
                n = n / 2;
            else
                n = 3 * n + 1;

            count++;
        }

        return count;
    }
}
